#!/bin/bash

r="\033[1;31m"
b="\033[1;34m"
w="\033[0m"

# Update DNS
sudo sed -i '/# Generated by NetworkManager/d' /etc/resolv.conf
echo "# University DNS records" | sudo tee -a /etc/resolv.conf > /dev/null
echo "nameserver 161.74.92.25" | sudo tee -a /etc/resolv.conf > /dev/null
echo "nameserver 161.74.92.50" | sudo tee -a /etc/resolv.conf > /dev/null
echo "# Google DNS records" | sudo tee -a /etc/resolv.conf > /dev/null
echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf > /dev/null

# Lock the DNS file
sudo chattr +i /etc/resolv.conf

# Set keyboard layout
sudo sed -i 's/^XKBLAYOUT=.*/XKBLAYOUT="gb"/' /etc/default/keyboard
sudo systemctl restart keyboard-setup.service

# Set timezone
sudo timedatectl set-timezone Europe/London

# Enable numlock in LightDM
if ! grep -q "greeter-setup-script=" /etc/lightdm/lightdm.conf; then
  sudo sed -i '/^\[Seat:\*/a greeter-setup-script=/usr/bin/numlockx on' /etc/lightdm/lightdm.conf
fi
